###
GET http://localhost:3000
###
GET http://localhost:3000/posts
###
GET http://localhost:3000/posts?sender=Amit
###
GET http://localhost:3000/posts/1
###

POST http://localhost:3000/posts 
Content-Type: application/json

{
"title": "Hello", "sender": "Amit", "content": "Hello World..."
}

###

DELETE http://localhost:3000/posts/1